### ISSUE TITLE
Support pyproject.toml and wheels

### ISSUE THREAD

**Issue by flying-sheep** [landscapeio/requirements-detector#24]
pyproject.toml is the new, but only standard way to build packages. Wheels offer a standard way to specify them (using a METADATA file)

So technically the only fool proof way to do this is to build a wheel using pyproject.toml and check that.

But alternatively we can just handle all known users:

```py
if config['build-backend'] == 'flit.buildapi':
    flit_meta = config['tool']['flit']['metadata']
    requirements = flit_meta['requires'] + [
        dep
        for extra, deps in flit_meta['requires-extra'].items()
        for dep in deps
    ]
elif config['build-backend'] == 'poetry.masonry.api':
    ... ['tool']['poetry']['dependencies']
...
```

**Comment by carlio** [comment]
Fixed in 1.0
