### ISSUE TITLE
find_requirements not accepting string on 1.0.2

### ISSUE THREAD

**Issue by danielzre** [landscapeio/requirements-detector#36]
Hi all, 
I think I found a bug in the latest release(1.0.2), on 0.7 the following code would run without any problem:

```
import os
from requirements_detector import find_requirements
find_requirements(os.getcwd())
```

But on 1.0.2 we get the following error:

`
TypeError: unsupported operand type(s) for /: 'str' and 'str'
`

It seems the function find_requirements does not accept a string anymore, only a Path object from pathlib. Can we make it compatible with 0.7.0 and accept both a Path object and a string?

Something like this should work:

```
def find_requirements(path: Union[Path, str]) -> List[DetectedRequirement]:
    requirements = []
    if isinstance(path, str):
        path = Path(path)
    setup_py = path / "setup.py"
    if path.exists() and path.is_file():
        try:
            requirements = from_setup_py(setup_py)
            requirements.sort()
            return requirements
```

Thanks.

**Comment by carlio** [comment]
> path: Union[Path, str]
The type is that - it is *supposed* to accept both! Thanks for the report, I will get a 1.0.3 release out ASAP (but probably not for a day)
Sorry about that, I thought I had enough tests to catch it.

**Comment by danielzre** [comment]
Hi Carlio, thanks for the fast response.

**Comment by carlio** [comment]
@danielzre 1.0.3 is on PyPI now and accepts string or Path for all public methods
