### ISSUE TITLE
KeyError when parsing pyproject.toml if git dependencies exist

### ISSUE THREAD

**Issue by bellmatt** [landscapeio/requirements-detector#38]
`requirements-detector` assumes `version` will always exist for each dependency in pyproject.toml, however this is not the case for git, path or url dependencies: 

https://python-poetry.org/docs/dependency-specification/#git-dependencies

For example, git dependencies in pyproject.toml can be specified without any version property (poetry assumes latest commit on main), or using branch, rev or tag, but not `version`.
```
mytestdependency = {git = "ssh://git@github.com/MyOrg/MyRepo.git",rev = "1.2.3"}
```

In this case, `requirements-detector` fails with a KeyError. 
```
  File "/repo/.venv/lib/python3.8/site-packages/requirements_detector/detect.py", line 68, in find_requirements
    requirements = from_pyproject_toml(poetry_toml)
  File "/repo/.venv/lib/python3.8/site-packages/requirements_detector/detect.py", line 116, in from_pyproject_toml
    spec = spec["version"]
KeyError: 'version'
```
The expected output would be to list `mytestdependency` without a version, or to attempt to parse the `rev` as the version

Relates to https://github.com/PyCQA/prospector/issues/556

**Comment by carlio** [comment]
Finally got around to merging and releasing this, sorry for the wait 

1.1.0 is on PyPI now (note it drops python 3.6 support to help with another issue #41 but from your stack trace it doesn't look like that matters for you!)
