### ISSUE TITLE
Unicode hack destroys indentation

### ISSUE THREAD

**Issue by Kriechi** [landscapeio/requirements-detector#5]
I was trying to use this tool on a `setup.py` file with valid syntax.
```python
# -*- coding: UTF-8 -*-
from distutils.core import setup

if foo:
    # just for a test with indentation
    bar()

setup(
    name=u'prospector-test-4-üéø',
    version='0.0.1',
    install_requires=[
        'Django==1.5.0',
        'django-gubbins==1.1.2'
    ]
)
```

Unfortunately [this hack](https://github.com/landscapeio/requirements-detector/blob/4ef161d4256a41abf51682973222a268aa7f44a2/requirements_detector/detect.py#L61) destroys the line indentation, and therefore produces invalid python code. This leads to an exception in AstroidBuilder (being catched [here](https://github.com/landscapeio/requirements-detector/blob/4ef161d4256a41abf51682973222a268aa7f44a2/requirements_detector/detect.py#L211)). 
Since parsing `setup.py` yielded an error, it falls back to parse `requirements.txt` - which in my case is empty.

**Proposed solution:**
Don't remove leading whitespace during `_load_file_contents`. I would have tried working on a fix myself, but I didn't quite understand the unicode hack involved here - I didn't want to break anything else...
Or is it enough to simply remove the `.strip()` from [here](https://github.com/landscapeio/requirements-detector/blob/4ef161d4256a41abf51682973222a268aa7f44a2/requirements_detector/detect.py#L61)?

**Comment by carlio** [comment]
Finally fixed in version 0.5.1 now on PyPi :)
