### ISSUE TITLE
unable to detect requirements in the "requirements-detector"

### ISSUE THREAD

**Issue by balusarakesh** [landscapeio/requirements-detector#6]
I tried to detect `requirements` in `setup.py` file at `https://github.com/landscapeio/requirements-detector/blob/master/setup.py`, but I'm getting the error
`Unable to find requirements at /***/Downloads/requirements-detector`. 

if the setup.py is in this format 
`setup( install_requires=install_requires,)`
it isn't working, it works only with this format 
`setup(install_requires=['requests', 'CAGE'],)`

**Comment by carlio** [comment]
Fixed in 1.0
