### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/requirements-detector#7]
The [license file](https://github.com/landscapeio/requirements-detector/blob/77d50db5e1a86f6d4e6e97446792854580c7fa81/LICENSE) says MIT. However, [`setup.py`](https://github.com/landscapeio/requirements-detector/blob/77d50db5e1a86f6d4e6e97446792854580c7fa81/setup.py#L24) says GPL 2. FWIW it seems `astroid` is the old requirement and seems to be LGPL for the version specified (unless we are talking 0.x versions). So it doesn't seem to constrain this at all. Given all of this, what is the license of `requirements-detector`?

**Comment by carlio** [comment]
@jakirkham  I think this was actually a mistake when copying classifiers from another project while I was making it python 3 compatible: https://github.com/landscapeio/requirements-detector/commit/aa17279791a1327ea44047179969402765ce372d#diff-2eeaed663bd0d25b7e608891384b7298R21

It was originally supposed to say MIT (and the Licence is set to that in the [call to setup](https://github.com/landscapeio/requirements-detector/blob/master/setup.py#L48). So basically it just has the wrong trove classifier. I can fix that easily enough, but the Licence is definitely supposed to be MIT.

**Comment by jakirkham** [comment]
Thanks for confirming as MIT, @carlio. Leaving open for the trove classifier fix.

**Comment by jakirkham** [comment]
Should be fixed by PR ( https://github.com/landscapeio/requirements-detector/pull/8 ).

**Comment by jakirkham** [comment]
Should also ask is the [copyright]( https://github.com/landscapeio/requirements-detector/blob/8c53b56cf3e29e97f555e9cf3be1b83fddca919a/LICENSE#L3 ) correct or is this a copy-pasta issue? It attributes it to Google and the AngularJS project.

**Comment by carlio** [comment]
@jakirkham Hmm no idea how that got there, must be copypasta. I'll remove.

**Comment by jakirkham** [comment]
This appears to be resolved now. Closing...
